@set-cookie = true


### test server
GET http://localhost:3327 HTTP/1.1

### register
POST http://localhost:3327/api/v1/users HTTP/1.1
Host: localhost:3327
content-type: application/json

{
    "nickname":"marcela",
    "name":"Marcela G M Albuquerque",
    "birthdate":"2007-06-29",
    "email":"ma@mail.com",
    "password":"MyPassw0rd#2023"
}

### auth
POST http://localhost:3327/api/v1/users/auth HTTP/1.1
Host: localhost:3327
content-type: application/json

{
    "email":"my@mail.com",
    "password":"MyPassw0rd#2023"
}

### get all users
GET http://localhost:3327/api/v1/users HTTP/1.1
Cookie: token=eyInvalidToken
