@set-cookie = true


### test server
GET http://localhost:3327 HTTP/1.1

### register
POST http://localhost:3327/api/v1/users HTTP/1.1
Host: localhost:3327
content-type: application/json

{
    "nickname":"Mia Lina",
    "name":"mia",
    "birthdate":"2007-06-29",
    "gender":"F",
    "email":"mia@mail.com",
    "password":"MyPassw0rd#2023"
}

### auth
POST http://localhost:3327/api/v1/users/auth HTTP/1.1
Host: localhost:3327
content-type: application/json

{
    "email":"lu@mail.com",
    "password":"MyPassw0rd#2023"
}

### get all users
GET http://localhost:3327/api/v1/users HTTP/1.1


### my users
GET http://localhost:3327/api/v1/users/my HTTP/1.1

